# The URL the site will be built for
base_url = "https://errantthinking.com"

title = "Errant Thinking"
author = "Errant Thinking"
description = "Asking insightful questions. Seeking thoughtful answers."
compile_sass = true
build_search_index = true
#generate_feed = true

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
render_emoji = true

external_links_target_blank = true

lazy_async_image = true

[extra]
author = "Errant Thinking"
# Put all your custom variables here
katex_enable = true
katex_auto_render = true

even_title = "Errant Thinking  :]"
even_menu = [
#    {url = "$BASE_URL", name = "Home"},
#    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
